### ISSUE TITLE
Update pgxn extension version

### ISSUE THREAD

**Issue by rngadam** [EnterpriseDB/mongo_fdw#83]
Current version is from 2013-11-18

MacOS X 10.12.6

```
 pgxn --version
pgxnclient 1.2.1
```

Install: ```pgxn install mongo_fdw```

error:

```
INFO: best version: mongo_fdw 2.0.0
INFO: saving /var/folders/5m/r1mjjrbx1pj0r41l8bptt15c0000gn/T/tmphFZOEr/mongo_fdw-2.0.0.zip
INFO: unpacking: /var/folders/5m/r1mjjrbx1pj0r41l8bptt15c0000gn/T/tmphFZOEr/mongo_fdw-2.0.0.zip
ERROR: unexpected error: OSError - [Errno 17] File exists: '/var/folders/5m/r1mjjrbx1pj0r41l8bptt15c0000gn/T/tmphFZOEr/mongo_fdw-2.0.0/mongo-c-driver-v0.6/docs/source/sphinx/source'
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pgxnclient-1.2.1-py2.7.egg/pgxnclient/cli.py", line 59, in script
    main(args)
  File "/Library/Python/2.7/site-packages/pgxnclient-1.2.1-py2.7.egg/pgxnclient/cli.py", line 31, in main
    run_command(opt, parser)
  File "/Library/Python/2.7/site-packages/pgxnclient-1.2.1-py2.7.egg/pgxnclient/commands/__init__.py", line 96, in run_command
    return opts.cmd(opts, parser=parser).run()
  File "/Library/Python/2.7/site-packages/pgxnclient-1.2.1-py2.7.egg/pgxnclient/commands/install.py", line 149, in run
    return super(SudoInstallUninstall, self).run()
  File "/Library/Python/2.7/site-packages/pgxnclient-1.2.1-py2.7.egg/pgxnclient/commands/install.py", line 100, in run
    return self._run(dir)
  File "/Library/Python/2.7/site-packages/pgxnclient-1.2.1-py2.7.egg/pgxnclient/commands/install.py", line 111, in _run
    pdir = archive.from_file(fn).unpack(dir)
  File "/Library/Python/2.7/site-packages/pgxnclient-1.2.1-py2.7.egg/pgxnclient/zip.py", line 66, in unpack
    os.makedirs(fname)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/var/folders/5m/r1mjjrbx1pj0r41l8bptt15c0000gn/T/tmphFZOEr/mongo_fdw-2.0.0/mongo-c-driver-v0.6/docs/source/sphinx/source'
```

**Comment by rngadam** [comment]
duplicate of issue #41
